name: Atualizar linguagens do README

on:
  schedule:
    - cron: '0 0 * * *' # Executa todo dia à meia-noite UTC
  workflow_dispatch:     # Permite execução manual
  push:
    branches:
      - main             # Troque para "master" se for sua branch principal

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Atualizar linguagens no README
        uses: DimaTc/readme-stats-updater@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit das alterações
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Atualiza linguagens do README automaticamente" || echo "Sem alterações"
          git push
